language: python

python:
  - '3.10'

branches:
  only:
    - stating

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings"

services:
  - postgresql

script:
  - python manage.py test
